---
title: Sondeo Medios - test
author: Jcib
date: '2022-01-30'
slug: []
categories:
  - R
tags:
  - test
  - sondeo
---

Tabla de contenidos de medios argentinos mediante RSS.
---

Si no aparece, el **formato de fecha** desde-hasta es: **2021-11-20 ... 2022-02-07**

```{r lib, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(tidyr)
library(magrittr)
library(DT)
```

```{r tabla, include=FALSE}
tabla <- read_csv("pre_tabla.csv") 

tabla$medio <- as.factor(tabla$medio)
```

## Noticias:

Filtrar según medio, fecha, o palabras clave. El buscador de arriba a la derecha permite buscar en todas las columnas.

```{r dt plot, echo=FALSE, message=FALSE, warning=FALSE}

DT::datatable(tabla, filter = 'top', 
              escape = FALSE, 
              class = 'cell-border stripe',
              options = list(pageLength = 50, autoWidth = TRUE,
                             columnDefs = list(list(width = '200px', targets = 3)),
                             initComplete = JS(
              "function(settings, json) {",
              "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
              "}")),
               rownames = FALSE
              )

# datatable(head(iris, 20), options = list(
#   initComplete = JS(
#     "function(settings, json) {",
#     "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
#     "}")
# ))
```
